#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Mon Apr 20 17:35:23 2026

add_design "D:/desktop/aaa/source/feifei/axi_arbiter.v"
add_design "D:/desktop/aaa/source/feifei/axi_m.v"
add_design "D:/desktop/aaa/source/feifei/rw_fifo_ctrl.v"
add_design "D:/desktop/aaa/source/AXI/fram_buf.v"
add_design "D:/desktop/aaa/source/AXI/fram_buf_rd_only.v"
add_design "D:/desktop/aaa/source/AXI/fram_buf_wr_only.v"
add_design "D:/desktop/aaa/source/AXI/multi_wr_single_rd_fram_buf_top.v"
add_design "D:/desktop/aaa/source/AXI/rd_buf.v"
add_design "D:/desktop/aaa/source/AXI/rd_ctrl.v"
add_design "D:/desktop/aaa/source/AXI/wr_arbiter_4to1.v"
add_design "D:/desktop/aaa/source/AXI/wr_buf.v"
add_design "D:/desktop/aaa/source/AXI/wr_cmd_trans.v"
add_design "D:/desktop/aaa/source/AXI/wr_ctrl.v"
add_design "D:/desktop/aaa/source/AXI/wr_rd_ctrl_top.v"
add_design "D:/desktop/aaa/source/cmos/cmos_8_16bit.v"
add_design "D:/desktop/aaa/source/cmos/i2c_com.v"
add_design "D:/desktop/aaa/source/cmos/power_on_delay.v"
add_design "D:/desktop/aaa/source/cmos/reg_config.v"
add_design "D:/desktop/aaa/source/rtl/cmos_8_16bit.v"
add_design "D:/desktop/aaa/source/hdmi/iic_dri.v"
add_design "D:/desktop/aaa/source/hdmi/ms7200_ctl.v"
add_design "D:/desktop/aaa/source/hdmi/ms7210_ctl.v"
add_design "D:/desktop/aaa/source/hdmi/ms72xx_ctl.v"
add_design "D:/desktop/aaa/source/rtl/hdmi_ddr_ov5640_top.v"
add_design "D:/desktop/aaa/source/rtl/top.v"
add_design "D:/desktop/aaa/source/rtl/top_new.v"
add_design "D:/desktop/aaa/source/video_process/rgb2yuv.v"
add_design "D:/desktop/aaa/source/video_process/sync_vg.v"
add_design "D:/desktop/aaa/source/video_process/video_enhance.v"
add_design "D:/desktop/aaa/source/video_process/video_zoom.v"
add_design "D:/desktop/aaa/source/video_process/yuv2rgb.v"
add_design "D:/desktop/aaa/source/interpolation_ram/interpolation_ram.idf"
add_design "D:/desktop/aaa/source/pll/pll.idf"
add_design "D:/desktop/aaa/source/rd_fram_buf/rd_fram_buf.idf"
add_design "D:/desktop/aaa/source/read_ddr_fifo/read_ddr_fifo.idf"
add_design "D:/desktop/aaa/source/wr_fram_buf/wr_fram_buf.idf"
add_design "D:/desktop/aaa/source/write_ddr_fifo/write_ddr_fifo.idf"
add_design "D:/desktop/OV5640_100h_backup_3/ipcore/ddr3_100h/ddr3_100h.idf"
add_design "D:/desktop/OV5640_100h_backup_3/ipcore/ddr3_test/ddr3_test.idf"
remove_design -verilog "D:/desktop/aaa/source/rtl/top_new.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/cmos_8_16bit.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module fram_buf
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "D:/desktop/aaa/source/OV5640_100h_backup_3/HDMI_DDR3_OV5640_test.fdc"
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
add_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
remove_design -verilog "D:/desktop/aaa/source/cmos/cmos_8_16bit.v"
remove_design -verilog "D:/desktop/aaa/source/cmos/i2c_com.v"
remove_design -verilog "D:/desktop/aaa/source/hdmi/ms72xx_ctl.v"
remove_design -verilog "D:/desktop/aaa/source/cmos/power_on_delay.v"
remove_design -verilog "D:/desktop/aaa/source/cmos/reg_config.v"
add_design "D:/desktop/aaa/source/source/aaa_top/cmos_8_16bit.v"
add_design "D:/desktop/aaa/source/source/aaa_top/hdmi_ddr_ov5640_top.v"
add_design "D:/desktop/aaa/source/source/aaa_top/top.v"
add_design "D:/desktop/aaa/source/source/aaa_top/top_new.v"
add_design "D:/desktop/aaa/source/source/aaa_video_process/rgb2yuv.v"
add_design "D:/desktop/aaa/source/source/aaa_video_process/sync_vg.v"
add_design "D:/desktop/aaa/source/source/aaa_video_process/video_enhance.v"
add_design "D:/desktop/aaa/source/source/aaa_video_process/video_zoom.v"
add_design "D:/desktop/aaa/source/source/aaa_video_process/yuv2rgb.v"
add_design "D:/desktop/aaa/source/source/axi/axi_m.v"
add_design "D:/desktop/aaa/source/source/axi/axi_m_arbitration.v"
add_design "D:/desktop/aaa/source/source/axi/rw_fifo_ctrl.v"
add_design "D:/desktop/aaa/source/source/cmos/cmos_8_16bit.v"
add_design "D:/desktop/aaa/source/source/cmos/i2c_com.v"
add_design "D:/desktop/aaa/source/source/cmos/power_on_delay.v"
add_design "D:/desktop/aaa/source/source/cmos/reg_config.v"
add_design "D:/desktop/aaa/source/source/fram_buf_myself/fram_buf_rd_only.v"
add_design "D:/desktop/aaa/source/source/fram_buf_myself/fram_buf_wr_only.v"
add_design "D:/desktop/aaa/source/source/fram_buf_myself/multi_wr_single_rd_fram_buf_top.v"
add_design "D:/desktop/aaa/source/source/fram_buf_myself/wr_arbiter_4to1.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/fram_buf.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/rd_buf.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/rd_ctrl.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/wr_buf.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/wr_cmd_trans.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/wr_ctrl.v"
add_design "D:/desktop/aaa/source/source/fram_buf_old/wr_rd_ctrl_top.v"
add_design "D:/desktop/aaa/source/source/hdmi/iic_dri.v"
add_design "D:/desktop/aaa/source/source/hdmi/ms7200_ctl.v"
add_design "D:/desktop/aaa/source/source/hdmi/ms7210_ctl.v"
add_design "D:/desktop/aaa/source/source/hdmi/ms72xx_ctl.v"
add_design "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram.v"
add_design "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tb.v"
add_design "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tmpl.v"
add_design "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tmpl.vhdl"
add_design "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_interpolation_ram.v"
add_design "D:/desktop/aaa/source/source/pll/pll.v"
add_design "D:/desktop/aaa/source/source/pll/pll_tb.v"
add_design "D:/desktop/aaa/source/source/pll/pll_tmpl.v"
add_design "D:/desktop/aaa/source/source/pll/pll_tmpl.vhdl"
add_design "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf.v"
add_design "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tb.v"
add_design "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tmpl.v"
add_design "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tmpl.vhdl"
add_design "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_rd_fram_buf.v"
add_design "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo.v"
add_design "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tb.v"
add_design "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tmpl.v"
add_design "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tmpl.vhdl"
add_design "D:/desktop/aaa/source/rtl/ipm2l_fifo_ctrl_v1_1_read_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/ipm2l_fifo_v1_10_read_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_read_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/read_ddr_fifo_Reset_Value.v"
add_design "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_wr_fram_buf.v"
add_design "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf.v"
add_design "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tb.v"
add_design "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tmpl.v"
add_design "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tmpl.vhdl"
add_design "D:/desktop/aaa/source/rtl/ipm2l_fifo_ctrl_v1_1_write_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/ipm2l_fifo_v1_10_write_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_write_ddr_fifo.v"
add_design "D:/desktop/aaa/source/rtl/write_ddr_fifo_Reset_Value.v"
add_design "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo.v"
add_design "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tb.v"
add_design "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tmpl.v"
add_design "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/source/aaa_top/top_new.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_myself/multi_wr_single_rd_fram_buf_top.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/fram_buf.v"
remove_design -verilog "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tb.v"
remove_design -verilog "D:/desktop/aaa/source/source/pll/pll_tb.v"
remove_design -verilog "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tb.v"
remove_design -verilog "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tb.v"
remove_design -verilog "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tb.v"
remove_design -verilog "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tb.v"
remove_design -verilog "D:/desktop/aaa/source/hdmi/iic_dri.v"
remove_design -verilog "D:/desktop/aaa/source/source/aaa_top/top.v"
remove_design -verilog "D:/desktop/aaa/source/source/aaa_top/cmos_8_16bit.v"
remove_design -verilog "D:/desktop/aaa/source/hdmi/ms7210_ctl.v"
remove_design -verilog "D:/desktop/aaa/source/hdmi/ms7200_ctl.v"
remove_design D:/desktop/OV5640_100h_backup_3/ipcore/ddr3_100h/ddr3_100h.idf
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/wr_buf.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_myself/fram_buf_rd_only.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_myself/fram_buf_wr_only.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_myself/wr_arbiter_4to1.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/wr_rd_ctrl_top.v"
remove_constraint  -logic -fdc "D:/desktop/aaa/source/OV5640_100h_backup_3/HDMI_DDR3_OV5640_test.fdc"
add_constraint "D:/desktop/aaa/source/fdc/HDMI_DDR3_OV5640_test.fdc"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/rd_buf.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/rd_ctrl.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/wr_cmd_trans.v"
remove_design -verilog "D:/desktop/aaa/source/source/fram_buf_old/wr_ctrl.v"
remove_design -verilog "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf.v"
remove_design -verilog "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_rd_fram_buf.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_wr_fram_buf.v"
remove_design D:/desktop/aaa/source/rd_fram_buf/rd_fram_buf.idf
remove_design D:/desktop/aaa/source/wr_fram_buf/wr_fram_buf.idf
remove_design -verilog "D:/desktop/aaa/source/feifei/axi_arbiter.v"
remove_design -verilog "D:/desktop/aaa/source/feifei/axi_m.v"
remove_design -verilog "D:/desktop/aaa/source/feifei/rw_fifo_ctrl.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/fram_buf.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/fram_buf_rd_only.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/fram_buf_wr_only.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/multi_wr_single_rd_fram_buf_top.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/rd_buf.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/rd_ctrl.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/wr_arbiter_4to1.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/wr_buf.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/wr_cmd_trans.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/wr_ctrl.v"
remove_design -verilog "D:/desktop/aaa/source/AXI/wr_rd_ctrl_top.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/hdmi_ddr_ov5640_top.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/top.v"
remove_design -verilog "D:/desktop/aaa/source/video_process/rgb2yuv.v"
remove_design -verilog "D:/desktop/aaa/source/video_process/sync_vg.v"
remove_design -verilog "D:/desktop/aaa/source/video_process/video_enhance.v"
remove_design -verilog "D:/desktop/aaa/source/video_process/video_zoom.v"
remove_design -verilog "D:/desktop/aaa/source/video_process/yuv2rgb.v"
remove_design -verilog "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/interpolation_ram/interpolation_ram_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/source/pll/pll_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/pll/pll_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/rd_fram_buf/rd_fram_buf_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/read_ddr_fifo/read_ddr_fifo_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/rtl/read_ddr_fifo_Reset_Value.v"
remove_design -verilog "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/wr_fram_buf/wr_fram_buf_tmpl.vhdl"
remove_design -verilog "D:/desktop/aaa/source/rtl/write_ddr_fifo_Reset_Value.v"
remove_design -verilog "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tmpl.v"
remove_design -vhdl "D:/desktop/aaa/source/source/write_ddr_fifo/write_ddr_fifo_tmpl.vhdl"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
add_design "D:/desktop/aaa/source/aaa/source/read_ddr_fifo/read_ddr_fifo.idf"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_fifo_v1_10_write_ddr_fifo.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_fifo_ctrl_v1_1_write_ddr_fifo.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_write_ddr_fifo.v"
add_design D:/desktop/aaa/ipcore/write_ddr_fifo/write_ddr_fifo.idf
remove_design D:/desktop/aaa/ipcore/write_ddr_fifo/write_ddr_fifo.idf
remove_design D:/desktop/aaa/source/read_ddr_fifo/read_ddr_fifo.idf
remove_design D:/desktop/aaa/source/interpolation_ram/interpolation_ram.idf
remove_design D:/desktop/aaa/source/pll/pll.idf
remove_design D:/desktop/aaa/source/aaa/source/read_ddr_fifo/read_ddr_fifo.idf
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_read_ddr_fifo.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_fifo_ctrl_v1_1_read_ddr_fifo.v"
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_fifo_v1_10_read_ddr_fifo.v"
add_design D:/desktop/aaa/ipcore/read_ddr_fifo/read_ddr_fifo.idf
remove_design -verilog "D:/desktop/aaa/source/rtl/ipm2l_sdpram_v1_10_interpolation_ram.v"
add_design D:/desktop/aaa/ipcore/interpolation_ram/interpolation_ram.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
remove_design -verilog "D:/desktop/aaa/source/source/pll/pll.v"
add_design D:/desktop/aaa/ipcore/pll/pll.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
remove_fic "D:/desktop/aaa/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
add_design D:/desktop/aaa/ipcore/cmos_pll/cmos_pll.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {33.33M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_design "D:/desktop/aaa/source/cmos/i2c_dri.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_design "D:/desktop/aaa/source/aaa_video_process/matrix_3x3.v"
add_design "D:/desktop/aaa/source/aaa_video_process/rgb2yuv.v"
add_design "D:/desktop/aaa/source/aaa_video_process/sort3.v"
add_design "D:/desktop/aaa/source/aaa_video_process/sync_vg.v"
add_design "D:/desktop/aaa/source/aaa_video_process/video_enhance.v"
add_design "D:/desktop/aaa/source/aaa_video_process/video_process.v"
add_design "D:/desktop/aaa/source/aaa_video_process/video_zoom.v"
add_design "D:/desktop/aaa/source/aaa_video_process/yuv2rgb.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/sync_vg.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/video_enhance.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/video_process.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/video_zoom.v"
remove_design D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo.idf
remove_design D:/desktop/OV5640_100h_backup_3/ipcore/ddr3_test/ddr3_test.idf
remove_design D:/desktop/bbb/ipcore/read_ddr_fifo/read_ddr_fifo.idf
remove_design D:/desktop/bbb/ipcore/pll/pll.idf
remove_design D:/desktop/bbb/ipcore/cmos_pll/cmos_pll.idf
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/rgb2yuv.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/yuv2rgb.v"
remove_design D:/desktop/bbb/ipcore/interpolation_ram/interpolation_ram.idf
remove_constraint  -logic -fdc "D:/desktop/bbb/source/fdc/HDMI_DDR3_OV5640_test.fdc"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_top/hdmi_ddr_ov5640_top.v"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_video_process/rgb2yuv.v"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_video_process/sync_vg.v"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_video_process/video_enhance.v"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_video_process/video_zoom.v"
remove_design -verilog "D:/desktop/bbb/source/source/aaa_video_process/yuv2rgb.v"
remove_design -verilog "D:/desktop/bbb/source/source/axi/axi_m.v"
remove_design -verilog "D:/desktop/bbb/source/source/axi/axi_m_arbitration.v"
remove_design -verilog "D:/desktop/bbb/source/source/axi/rw_fifo_ctrl.v"
remove_design -verilog "D:/desktop/bbb/source/source/cmos/cmos_8_16bit.v"
remove_design -verilog "D:/desktop/bbb/source/source/cmos/i2c_com.v"
remove_design -verilog "D:/desktop/bbb/source/source/cmos/power_on_delay.v"
remove_design -verilog "D:/desktop/bbb/source/source/cmos/reg_config.v"
remove_design -verilog "D:/desktop/bbb/source/source/hdmi/iic_dri.v"
remove_design -verilog "D:/desktop/bbb/source/source/hdmi/ms7200_ctl.v"
remove_design -verilog "D:/desktop/bbb/source/source/hdmi/ms7210_ctl.v"
remove_design -verilog "D:/desktop/bbb/source/source/hdmi/ms72xx_ctl.v"
remove_design -verilog "D:/desktop/bbb/source/source/interpolation_ram/interpolation_ram.v"
remove_design -verilog "D:/desktop/bbb/source/source/read_ddr_fifo/read_ddr_fifo.v"
remove_design -verilog "D:/desktop/bbb/source/source/write_ddr_fifo/write_ddr_fifo.v"
remove_design -verilog "D:/desktop/bbb/source/cmos/i2c_dri.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/matrix_3x3.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/sort3.v"
add_constraint "D:/desktop/bbb/fdc/HDMI_DDR3_OV5640_test.fdc"
add_design "D:/desktop/bbb/source/aaa_top/cmos_8_16bit.v"
add_design "D:/desktop/bbb/source/aaa_top/hdmi_ddr_ov5640_top.v"
add_design "D:/desktop/bbb/source/aaa_top/top.v"
add_design "D:/desktop/bbb/source/aaa_top/top_new.v"
add_design "D:/desktop/bbb/source/aaa_video_process/rgb2yuv.v"
add_design "D:/desktop/bbb/source/aaa_video_process/sync_vg.v"
add_design "D:/desktop/bbb/source/aaa_video_process/video_enhance.v"
add_design "D:/desktop/bbb/source/aaa_video_process/video_process.v"
add_design "D:/desktop/bbb/source/aaa_video_process/video_zoom.v"
add_design "D:/desktop/bbb/source/aaa_video_process/yuv2rgb.v"
add_design "D:/desktop/bbb/source/axi/axi_m.v"
add_design "D:/desktop/bbb/source/axi/axi_m_arbitration.v"
add_design "D:/desktop/bbb/source/axi/rw_fifo_ctrl.v"
add_design "D:/desktop/bbb/source/cmos/cmos_8_16bit.v"
add_design "D:/desktop/bbb/source/cmos/i2c_com.v"
add_design "D:/desktop/bbb/source/cmos/power_on_delay.v"
add_design "D:/desktop/bbb/source/cmos/reg_config.v"
add_design "D:/desktop/bbb/source/hdmi/iic_dri.v"
add_design "D:/desktop/bbb/source/hdmi/ms7200_ctl.v"
add_design "D:/desktop/bbb/source/hdmi/ms7210_ctl.v"
add_design "D:/desktop/bbb/source/hdmi/ms72xx_ctl.v"
add_design "D:/desktop/bbb/source/interpolation_ram/interpolation_ram.v"
add_design "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tb.v"
add_design "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tmpl.v"
add_design "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tmpl.vhdl"
add_design "D:/desktop/bbb/source/pll/pll.v"
add_design "D:/desktop/bbb/source/pll/pll_tb.v"
add_design "D:/desktop/bbb/source/pll/pll_tmpl.v"
add_design "D:/desktop/bbb/source/pll/pll_tmpl.vhdl"
add_design "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo.v"
add_design "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tb.v"
add_design "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tmpl.v"
add_design "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tmpl.vhdl"
add_design "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo.v"
add_design "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tb.v"
add_design "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tmpl.v"
add_design "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tmpl.vhdl"
remove_design -verilog "D:/desktop/bbb/source/aaa_top/top.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_top/top_new.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/video_enhance.v"
add_design "D:/desktop/bbb/ipcore/cmos_pll/cmos_pll.idf"
add_design "D:/desktop/bbb/ipcore/interpolation_ram/interpolation_ram.idf"
add_design "D:/desktop/bbb/ipcore/pll/pll.idf"
add_design "D:/desktop/bbb/ipcore/read_ddr_fifo/read_ddr_fifo.idf"
add_design "D:/desktop/bbb/ipcore/write_ddr_fifo/write_ddr_fifo.idf"
remove_design -verilog "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tb.v"
remove_design -verilog "D:/desktop/bbb/source/pll/pll_tb.v"
remove_design -verilog "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tb.v"
remove_design -verilog "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tb.v"
remove_design D:/desktop/bbb/ipcore/write_ddr_fifo/write_ddr_fifo.idf
remove_design -verilog "D:/desktop/bbb/source/aaa_top/cmos_8_16bit.v"
remove_design -verilog "D:/desktop/bbb/source/interpolation_ram/interpolation_ram.v"
remove_design -verilog "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tmpl.v"
remove_design -vhdl "D:/desktop/bbb/source/interpolation_ram/interpolation_ram_tmpl.vhdl"
remove_design -verilog "D:/desktop/bbb/source/pll/pll.v"
remove_design -verilog "D:/desktop/bbb/source/pll/pll_tmpl.v"
remove_design -vhdl "D:/desktop/bbb/source/pll/pll_tmpl.vhdl"
remove_design -verilog "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo.v"
remove_design -verilog "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tmpl.v"
remove_design -vhdl "D:/desktop/bbb/source/read_ddr_fifo/read_ddr_fifo_tmpl.vhdl"
remove_design -verilog "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo.v"
remove_design -verilog "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tmpl.v"
remove_design -vhdl "D:/desktop/bbb/source/write_ddr_fifo/write_ddr_fifo_tmpl.vhdl"
add_design "D:/desktop/bbb/source/aaa_video_process/matrix_3x3.v"
add_design "D:/desktop/bbb/source/aaa_video_process/median_filter_3x3.v"
add_design "D:/desktop/bbb/source/aaa_video_process/sort3.v"
add_design "D:/desktop/bbb/source/aaa_video_process/video_enhance.v"
remove_design -verilog "D:/desktop/bbb/source/aaa_video_process/video_enhance.v"
add_design D:/desktop/bbb/ipcore/write_ddr_fifo/write_ddr_fifo.idf
add_design "D:/desktop/bbb/ipcore/ddr3_test/ddr3_test.idf"
add_design "D:/desktop/bbb/ipcore/fifo_line_buf/fifo_line_buf.idf"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_design D:/ZGTC/Work/ccc/ipcore/eth_pkt_fifo/eth_pkt_fifo.idf
add_design "D:/ZGTC/Work/ccc/source/fei_eth/crc32_d8.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/eth_img_pkt.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/eth_img_rec.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/gmii_to_rgmii.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/rw_fifo_ctrl.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/udp_rx.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/udp_top.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/udp_tx.v"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/vesa_debug.v"
remove_design -verilog "D:/ZGTC/Work/ccc/source/fei_eth/rw_fifo_ctrl.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
add_design "D:/ZGTC/Work/ccc/ipcore/ref_clock/ref_clock.idf"
add_design "D:/ZGTC/Work/ccc/source/fei_eth/rgmii_interface.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
add_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
remove_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
add_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
add_fic "D:/ZGTC/Work/ccc/synthesize/hdmi_ddr_ov5640_top_syn.fic"
dev_map 
dev_map 
dev_map 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_design D:/ZGTC/Work/ccc/ipcore/watch_clk/watch_clk.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
add_design "D:/ZGTC/Work/ccc/source/dynamic_delay.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module hdmi_ddr_ov5640_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr -mode {performance} -optimize_multi_corner_timing -fix_hold_violation 
report_timing 
gen_bit_stream -master_configuration_clock_frequency {25M} 
